### ISSUE TITLE
Sketch Toolbox is missing this plugin?

### ISSUE THREAD

**Issue by gustaflindqvist** [sketch-hq/sketch-image-compressor#6]
Is this repo missing the `mainfest.json` file to get Sketch Toolbox to pick this plugin up?

**Comment by kdumovic** [comment]
+1

**Comment by batsper** [comment]
+1
is it missing the .sketchplugin file also?

**Comment by isnav** [comment]
+1

**Comment by tdzl** [comment]
Still not seeing the .sketchplugin file. Any update to this?

**Comment by alexchantastic** [comment]
Agreed, would be nice to have the `.sketchplugin` file added to the root of the repo so it can also be added to the [Sketch Runner](http://sketchrunner.com/) install/upgrade list.
